#!/bin/sh
CURRENT_DIR=$(dirname "$0")

cd $CURRENT_DIR
cd ..

python3 -B -m cards make $CURRENT_DIR/template/cards.csv -o $CURRENT_DIR -f template.html --verbose
python3 -B -m cards make $CURRENT_DIR/template/cards-no-template.csv -o $CURRENT_DIR -f template-missing.html --verbose
python3 -B -m cards make $CURRENT_DIR/template/cards-with-unused-fields.csv -o $CURRENT_DIR -f template-unused-fields.html --verbose
python3 -B -m cards make $CURRENT_DIR/template/cards-with-defs.csv -d $CURRENT_DIR/template/defs.csv -o $CURRENT_DIR -f template-defs.html --verbose
python3 -B -m cards make $CURRENT_DIR/template-field/cards.csv -o $CURRENT_DIR -f template-field.html --verbose
python3 -B -m cards make $CURRENT_DIR/image-field/cards.csv -o $CURRENT_DIR -f image-field.html --verbose
python3 -B -m cards make $CURRENT_DIR/image-field/cards-with-defs.csv -d $CURRENT_DIR/image-field/defs.csv -o $CURRENT_DIR -f image-field-defs.html --verbose
python3 -B -m cards make $CURRENT_DIR/count/cards.csv -o $CURRENT_DIR -f count.html --verbose
python3 -B -m cards make $CURRENT_DIR/count/cards-no-count.csv -o $CURRENT_DIR -f count-missing.html --verbose
